### ISSUE TITLE
cmake error cannot find source file ../src/common.cpp

### ISSUE THREAD

**Issue by szx0112** [bennihepp/Quad3DR#5]
Hi, I got the following error during the compiling.

`-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   serialization
-- A library with BLAS API found.
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "10.0") 
-- Found CUDA: /usr/local/cuda (found version "10.0") 
With profiling
Defining OPENCV_3_0 macro
-- Checking for module 'gstreamer-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-base-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-base-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-app-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-app-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-audio-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-audio-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-fft-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-fft-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-mpegts-1.0>=1.4.0'
--   No package 'gstreamer-mpegts-1.0' found
-- Checking for module 'gstreamer-pbutils-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-pbutils-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-tag-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-tag-1.0' in file '(command line arguments)'
-- Checking for module 'gstreamer-video-1.0 >= '
--   Comparison operator but no version after package name 'gstreamer-video-1.0' in file '(command line arguments)'
-- Could NOT find SQLITE3 (missing: SQLITE3_LIBRARY) 
-- Configuring done
CMake Error at video/CMakeLists.txt:73 (add_executable):
  Cannot find source file:

    ../src/common.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: video_streamer_bundlefusion
CMake Error: Cannot determine link language for target "video_streamer_bundlefusion".
-- Generating done
-- Build files have been written to: /home/szx/Quad3DR/build
`

Any comment is appreciated.

**Comment by wudiliyao** [comment]
I have the same problem and I want to know how you solve it
